CREATE DATABASE School;
USE School;
CREATE TABLE Student(Roll_No INT PRIMARY KEY, Student_Name VARCHAR(30), Marks INT, Grade VARCHAR(1));
DESC Student;
INSERT INTO Student VALUES(1,'Arya',95,'A');
INSERT INTO Student VALUES(2,'Amal',85,'B');
INSERT INTO Student VALUES(3,'Bibin',73,'C');
INSERT INTO Student VALUES(4,'Babu',55,'E');
INSERT INTO Student VALUES(5,'David',40,'F');
INSERT INTO Student VALUES(6,'Dhanya',99,'A');
INSERT INTO Student VALUES(7,'Fasil',88,'B');
INSERT INTO Student VALUES(8,'Ganga',72,'C');
INSERT INTO Student VALUES(9,'Hari',32,'F');
INSERT INTO Student VALUES(10,'Jacob',66,'D');
SELECT * FROM Student;
ALTER TABLE Student ADD COLUMN Contact VARCHAR(30);
ALTER TABLE Student DROP COLUMN Grade;
RENAME TABLE Student TO Classten;
TRUNCATE TABLE Classten;
SELECT * FROM Classten;
DROP TABLE Classten;