CREATE DATABASE Schooldb;
USE Schooldb;
CREATE TABLE Teachers(Tid INT PRIMARY KEY, T_Name VARCHAR(30), Age INT, Experience INT);
DESC Teachers;
INSERT INTO Teachers VALUES(1,'Arya',30,5);
INSERT INTO Teachers VALUES(2,'Vishnu',32,4);
INSERT INTO Teachers VALUES(3,'Nithya',31,3);
INSERT INTO Teachers VALUES(4,'David',30,2);
INSERT INTO Teachers VALUES(5,'Sudev',28,1);
ALTER TABLE Teachers ADD COLUMN Address VARCHAR(30);
SELECT * FROM Teachers;                                                                      
UPDATE Teachers SET Address = 'Abb' WHERE Tid = 1;
UPDATE Teachers SET Address = 'Bcc' WHERE Tid = 2;
UPDATE Teachers SET Address = 'Cdd' WHERE Tid = 3;
UPDATE Teachers SET Address = 'Dee' WHERE Tid = 4;
UPDATE Teachers SET Address = 'Eff' WHERE Tid = 5;
INSERT INTO Teachers VALUES(6,'Ajmal',40,8,'Fgg');
DELETE FROM Teachers WHERE Tid = 6;
DROP TABLE Teachers;
CREATE TABLE Teachers(Tid INT PRIMARY KEY, T_Name VARCHAR(30) NOT NULL, Age INT, Experience INT);
INSERT INTO Teachers VALUES(7,'',28,4);